unique_name: PRODUCTDATA
object_type: dataset
label: PRODUCTDATA
columns:
  - name: BRAND
    data_type: string
  - name: CATEGORY
    data_type: string
  - name: COLOR
    data_type: string
  - name: DESCRIPTION
    data_type: string
  - name: DIMENSIONS
    data_type: string
  - name: PRICE
    data_type: decimal(38,2)
  - name: PRODUCT_NAME
    data_type: string
  - name: QUANTITY
    data_type: decimal(38,0)
  - name: RELEASE_DATE
    data_type: date
  - name: WEIGHT
    data_type: decimal(38,2)
connection_id: con_RETAIL_WEB
table: PRODUCTDATA
